# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'TestActionDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestActionDemo
	pod 'Masonry'

  target 'TestActionDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestActionDemoUITests' do
    # Pods for testing
  end

end
